name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    strategy:
      matrix:
        deno:
          - v1.37.1
        platform:
          - os: ubuntu-latest
            arch: x86_64
            tag: linux-gnu
          - os: macOS-latest
            arch: x86_64
            tag: darwin
          - os: windows-latest
            arch: x86_64
            tag: windows
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - if: matrix.platform.tag != 'windows'
        name: Set build env
        run: echo "BUILD_NAME=tsd-searcher-${{ github.ref_name }}-${{ matrix.platform.arch }}-${{ matrix.platform.tag }}" >> $GITHUB_ENV
      - if: matrix.platform.tag == 'windows'
        name: Set build env
        run: echo "BUILD_NAME=tsd-searcher-${{ github.ref_name }}-${{ matrix.platform.arch }}-${{ matrix.platform.tag }}" >> $Env:GITHUB_ENV
      - name: Compile
        run: deno task build
      - if: matrix.platform.tag != 'windows'
        name: Tar build
        working-directory: build
        run: tar zcvf ${{ env.BUILD_NAME }}.tar.gz tsd-searcher
      - if: matrix.platform.tag == 'windows'
        name: Tar build
        working-directory: build
        run: tar zcvf ${{ env.BUILD_NAME }}.tar.gz tsd-searcher.exe
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_NAME }}
          path: build/${{ env.BUILD_NAME }}.tar.gz
          retention-days: 1
