name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  cq:
    name: Code Quality
    strategy:
      matrix:
        deno:
          - v1.37.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - name: lint
        run: deno lint
      - name: fmt
        run: deno fmt --check
  validate:
    name: Validate
    strategy:
      matrix:
        deno:
          - v1.37.1
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - name: Unit test
        run: deno task test

  required:
    runs-on: ubuntu-latest
    name: Required
    needs:
      - cq
      - validate
    steps:
      - run: echo All required jobs succeeded.
